from typing import Protocol
class WebcastProviderAdapter(Protocol):
    name: str
    async def matches(self, page) -> bool: ...
    async def handle_registration(self, page, profile, event, submitted) -> bool: ...
    async def discover_media(self, page): ...
    async def find_official_transcript(self, page): ...
