"""Require evaluated macro imports to match the configured upstream workbook."""

import logging
import os
import re
import time
from google_sheets import a1, column_name
from validation import ValidationError


def canonical(rows):
    result = [list(row) for row in rows]
    for row in result:
        while row and row[-1] == "":
            row.pop()
    while result and not result[-1]:
        result.pop()
    return result


def check_summary_selectors(headers, helpers, expected_score):
    """Audit the existing 37-pair macro summary layout before publication."""
    if len(headers) != 38 or headers[0] != "Date" or len(set(headers[1:])) != 37:
        raise ValidationError(
            "Macro summary must contain Date and 37 unique indicator headers"
        )
    if len(helpers) < 2:
        raise ValidationError("Macro summary helper formulas are missing")
    for index, indicator in enumerate(headers[1:]):
        offset = index * 2
        cell = column_name(40 + offset)
        heading = helpers[0][offset] if offset < len(helpers[0]) else ""
        formula = helpers[1][offset] if offset < len(helpers[1]) else ""
        compact = re.sub(r"\s+", "", formula) if isinstance(formula, str) else ""
        selector = (
            re.findall(r'scoreCol\s*,\s*MATCH\(\s*"([^"]+)"', formula, re.I)
            if isinstance(formula, str)
            else []
        )
        if (
            heading != "=" + column_name(index + 2) + "1"
            or f"sheet,{cell}1," not in compact
            or selector != [expected_score]
        ):
            raise ValidationError(
                f"{expected_score}!{cell}2 ({indicator}): expected {expected_score}; "
                f'found {selector or "unrecognised mapping"}. Correct the macro summary before publishing.'
            )


def validate_macro_summary(sheets, book):
    source_id = os.getenv(
        "GOOGLE_SPREADSHEET_ID", "19E_Za0DOHMY_9AFSPatK8Cp2vCQypI81QnB3Hz4ve9c"
    )
    headers = sheets.values(source_id, [a1(book.macro_tab, "A1:AL1")])[0]
    helpers = sheets.values(source_id, [a1(book.macro_tab, "AN1:DI2")], formulas=True)[
        0
    ]
    check_summary_selectors(headers[0] if headers else [], helpers, book.macro_tab)
    logging.info("%s: verified all 37 macro summary score selections", book.macro_tab)


def wait_for_macro(sheets, book, attempts=12, delay=10):
    anchor = sheets.values(
        book.spreadsheet_id, [a1(book.source_tab, "A1")], formulas=True
    )[0]
    formula = anchor[0][0] if anchor and anchor[0] else ""
    match = re.fullmatch(
        r'\s*=IMPORTRANGE\("([^"]+)"\s*[,;]\s*"([^"]+)"\)\s*', formula, re.I
    )
    if not match:
        raise ValidationError(
            f"{book.key}: expected a single IMPORTRANGE source at A1; inspect source mapping"
        )
    origin, source_range = match.groups()
    source_id = origin.split("/d/")[1].split("/")[0] if "/d/" in origin else origin
    expected = os.getenv(
        "GOOGLE_SPREADSHEET_ID", "19E_Za0DOHMY_9AFSPatK8Cp2vCQypI81QnB3Hz4ve9c"
    )
    if source_id != expected:
        raise ValidationError(
            f"{book.key}: source import points to a different macro workbook"
        )
    imported_tab = source_range.rsplit("!", 1)[0].strip("'")
    if imported_tab != book.macro_tab:
        raise ValidationError(
            f"{book.key}: expected {book.macro_tab}, found {imported_tab}; wrong score dataset"
        )
    for attempt in range(attempts):
        upstream = sheets.values(source_id, [source_range])[0]
        imported = sheets.values(book.spreadsheet_id, [a1(book.source_tab)])[0]
        if upstream and canonical(upstream) == canonical(imported):
            return imported
        if attempt + 1 < attempts:
            logging.info(
                "%s: waiting for refreshed macro scores (%s/%s)",
                book.key,
                attempt + 1,
                attempts,
            )
            time.sleep(delay)
    raise ValidationError(
        f"{book.key}: macro import is stale or loading; downstream publication stopped"
    )


def prepare_dataset_links(sheets, book, run_dir):
    """Correct copied LEAD date/source metadata only inside the new workbooks.

    Momentum import anchors are generated by momentum_pipeline.prepare using the
    dataset-qualified upstream map. Save their original state before it runs.
    Numerical controls, pair definitions and the macro workbook are untouched.
    """
    if book.dataset != "leading":
        return
    from config import upstream_book, window_value, momentum_lookback

    meta = sheets.metadata(book.spreadsheet_id)
    tabs = {s["properties"]["title"]: s["properties"] for s in meta["sheets"]}
    if tabs.get(book.output_tab, {}).get("sheetId") != book.output_id:
        raise ValidationError(f"{book.key}: output sheet identity changed")
    controls = sheets.values(book.spreadsheet_id, [a1(book.control_tab, "A1:B20")])[0]
    window_value(controls, book.control_key)
    changes = []
    if book.kind.endswith("_momentum"):
        momentum_lookback(controls)
        up = upstream_book(book)
        wait_for_macro(sheets, up)
        expected = {
            "Source Spreadsheet ID": up.spreadsheet_id,
            "Source Tab": (
                up.source_tab if book.kind == "spread_momentum" else up.output_tab
            ),
        }
        for key, value in expected.items():
            matches = [
                (i, row) for i, row in enumerate(controls, 1) if row and row[0] == key
            ]
            if len(matches) != 1:
                raise ValidationError(f"{book.key}: expected one {key} control")
            index, row = matches[0]
            if len(row) < 2 or row[1] != value:
                changes.append(
                    {"range": a1(book.control_tab, f"B{index}"), "values": [[value]]}
                )
        ranges = [a1(book.source_tab, "1:1"), a1(book.output_tab, "1:2")]
        if book.kind == "spread_momentum":
            ranges.append(a1("Imported Pair Definitions", "1:2"))
    else:
        wait_for_macro(sheets, book)
        ranges = [a1(book.output_tab, "A1:A2")]
        if book.kind == "spread":
            current = sheets.values(
                book.spreadsheet_id, [a1(book.output_tab, "A1")], formulas=True
            )[0]
            formula = current[0][0] if current and current[0] else ""
            # Repair the known copied coincident date formula. Existing leading
            # and local date formulas are not replaced merely for stylistic reasons.
            if "Coincident Score" in formula:
                changes.append(
                    {
                        "range": a1(book.output_tab, "A1"),
                        "values": [[f"=ARRAYFORMULA('{book.source_tab}'!A1:A)"]],
                    }
                )
    original = sheets.values(book.spreadsheet_id, ranges, formulas=True)
    sheets.backup(
        run_dir / (book.key + "_links_before.json.gz"),
        {
            "spreadsheet_id": book.spreadsheet_id,
            "metadata": meta,
            "ranges": ranges,
            "formulas": original,
            "controls": controls,
            "changes": changes,
        },
    )
    if changes:
        logging.info(
            "%s: correcting copied source/date links in %s",
            book.key,
            [c["range"] for c in changes],
        )
        sheets.request(
            "POST",
            book.spreadsheet_id,
            "/values:batchUpdate",
            json={"valueInputOption": "USER_ENTERED", "data": changes},
        )
        actual = sheets.values(
            book.spreadsheet_id, [c["range"] for c in changes], formulas=True
        )
        if actual != [c["values"] for c in changes]:
            raise ValidationError(f"{book.key}: source/date link readback failed")
